"""Add latest development to events

Revision ID: 21e4c34ac997
Revises: fb96563e02a2
Create Date: 2026-08-03 18:31:33.652004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e4c34ac997'
down_revision: Union[str, Sequence[str], None] = 'fb96563e02a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('latest_development', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'latest_development')
    # ### end Alembic commands ###
