"""Add event category

Revision ID: 5ef9b715ae66
Revises: b84b789ca6b2
Create Date: 2026-08-02 23:33:17.184814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef9b715ae66'
down_revision: Union[str, Sequence[str], None] = 'b84b789ca6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "events",
        sa.Column(
            "category",
            sa.String(length=50),
            nullable=False,
            server_default="Other",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
