"""Add needs refresh flag

Revision ID: 8ecd9829f12a
Revises: 5ef9b715ae66
Create Date: 2026-08-03 12:05:24.291637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecd9829f12a'
down_revision: Union[str, Sequence[str], None] = '5ef9b715ae66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "events",
        sa.Column(
            "needs_refresh",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'needs_refresh')
    # ### end Alembic commands ###
