"""Add event metrics

Revision ID: b84b789ca6b2
Revises: eb46fa984176
Create Date: 2026-08-02 23:19:21.667493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84b789ca6b2'
down_revision: Union[str, Sequence[str], None] = 'eb46fa984176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "events",
        sa.Column(
            "article_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "source_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'source_count')
    op.drop_column('events', 'article_count')
    # ### end Alembic commands ###
