"""Track processed event articles

Revision ID: bdb8979456e4
Revises: 21e4c34ac997
Create Date: 2026-08-03 18:37:08.548980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb8979456e4'
down_revision: Union[str, Sequence[str], None] = '21e4c34ac997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "articles",
        sa.Column(
            "processed_for_event",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.alter_column(
        "articles",
        "processed_for_event",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'processed_for_event')
    # ### end Alembic commands ###
