"""Add article editorial status

Revision ID: f9ca905b0dee
Revises: bdb8979456e4
Create Date: 2026-08-03 19:42:32.024508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ca905b0dee'
down_revision: Union[str, Sequence[str], None] = 'bdb8979456e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "articles",
        sa.Column(
            "editorial_status",
            sa.String(length=20),
            nullable=False,
            server_default="Pending",
        ),
    )

    op.alter_column(
        "articles",
        "editorial_status",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'editorial_status')
    # ### end Alembic commands ###
