"""Add editorial event fields

Revision ID: fa4e03c78fe6
Revises: 8ecd9829f12a
Create Date: 2026-08-03 13:54:04.820367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4e03c78fe6'
down_revision: Union[str, Sequence[str], None] = '8ecd9829f12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "events",
        sa.Column(
            "why_it_matters",
            sa.Text(),
            nullable=True,
        ),
    )

    op.add_column(
        "events",
        sa.Column(
            "what_happens_next",
            sa.Text(),
            nullable=True,
        ),
    )

    op.add_column(
        "events",
        sa.Column(
            "impact_scope",
            sa.String(length=50),
            nullable=False,
            server_default="Unknown",
        ),
    )

    op.add_column(
        "events",
        sa.Column(
            "confidence",
            sa.String(length=20),
            nullable=False,
            server_default="Developing",
        ),
    )

    op.add_column(
        "events",
        sa.Column(
            "homepage",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'homepage')
    op.drop_column('events', 'confidence')
    op.drop_column('events', 'impact_scope')
    op.drop_column('events', 'what_happens_next')
    op.drop_column('events', 'why_it_matters')
    # ### end Alembic commands ###
